### ISSUE TITLE
multipoolAutoswap revamp

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1632]
Largely parallel to #1586, but applies to mutlipoolAutoswap

* [x]  match autoswap API
* [x]  fix addLiquidity bug  (#1600)
* [x]  test using jig
* [x]  distinguish inputPrice/outputPrice
* [x]  distinguish swapIn/swapOut
* [x]  update API type declarations
* [x]  Verify that we share curve logic with autoswap
* [x]  review outstanding todos  (#428, #1539)
* [ ]  test using jig in swingset
* [ ]  test removeLiquidity (and #921)
* [ ]  add a todo for a notifier 
* [x]  contract documentation

fixes #1600 
closes: #428, #1539, #921

**Comment by Chris-Hibbert** [comment]
Closed by #1672.
