### ISSUE TITLE
AMM Roadmap

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1673]
PR #1672 was a major cleanup of multipoolAutoswap, but some work wasn't completed, including tests, some obvious opportunities for refactoring, and tooling.

Tests: 
 * [x] there are no swingset tests for multipool autoswap. These can probably use autoswapJig, which means passing `t` into the test.
    * The tests in `vpool-xyk-amm` set up contracts in separate vats, without swingset tests.
 * [x] testing removeLiquidity
 * [ ] requesting prices and trades for tokens that are not present
 * [ ] attempting to add pools for a non-NAT currency
 * [ ] [What happens to liqTokenSupply in add/remove liquidity](https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471035559) if the trade fails due to offer safety

Refactoring:
 * [x] swap.js is highly redundant, and can probably be simplified. There are 4 highly parallel copies of the code for trading between central and secondary (using `trade()`, and 2 ways of trading from secondary to secondary (using stages and `reallocate()`. ([one recommendation](https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471036706))
 * [ ] in `addPool()` [manage automatic generation of keywords](https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471035866) for the user from something like Secondary${nonce}?
 * [x] issue #1502:  atomic saveIssuer/makeZcfMint
 * [x] virtual pools to simplify code and support other kinds of exchanges #2259

Tooling:
 * [ ] We should add notifiers for price and liquidity changes. [2458](https://github.com/Agoric/agoric-sdk/issues/2458)

New Functionality:
 * [x] a variant of swapOut that eschews offerSafety in favor of doing the trade if the desired outputAmount won't be produced by the available inputAmount. (see comment below) #4321  (resolved by #5125)

Issue: 
 * [x] [TOCTOU error](https://github.com/Agoric/agoric-sdk/issues/1461) remains unresolved

**Comment by Chris-Hibbert** [comment]
The current algorithm for swapOut only pays out the amount requested, even when liquidating amountIn should provide more proceeds according to the price curve.

After 
```js
const amountIn = pool.getSecondaryToCentralOutputPrice(outputValue);
  ```
or 
``` js
const amountIn = pool.getCentralToSecondaryOutputPrice(outputValue);
```
it should recalculate amountIn as the min of `offeredAmountIn` and `amountIn`, and then reassign amountOut as
```js
amountOut = pool.getCentralToSecondaryInputPrice(amountIn.value);
```
or `getSecondaryToCentralIntputPrice()` respectively.  The secondary to secondary case should be similarly updated.

**Comment by Chris-Hibbert** [comment]
Dean suggests abstracting out pools to include virtualPools, which could represent multiple hops, as well as synthetic pools of other types (stable rates, for example). This should be designed so `getCurrentPrice()` and `swap()` can deal directly with a single pool rather than having explicit code to deal with trades in different directions and with one or two pools.

**Comment by Chris-Hibbert** [comment]
Dean also suggested that there should be a variant of swapOut that eschews offerSafety in favor of doing the trade if the desired outputAmount won't be produced by the available inputAmount.  Effectively: "please sell only as much of this inputAmount as necessary to produce outputAmount, but sell it all if it's not enough."

The current Vault contract has to make two successive calls to achieve this, and if the price changes in between, the price could have changed in the borrower's favor (meaning that after the delay they didn't need to sell everything) or to their detriment (meaning that the lapse of time hurt them.)

**Comment by katelynsills** [comment]
Some of this may be in Beta, @Chris-Hibbert  to follow up

**Comment by rowgraus** [comment]
Should move generic checklist type issues into existing (or new) epics

**Comment by Tartuffo** [comment]
This was added back to Mainnet 1 because we wanted to get this work done before the Purple Team review.

**Comment by turadg** [comment]
Obsolete since we removed the AMM.
