### ISSUE TITLE
xsnap security audit

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2468]
Some of us including @warner , @dtribble discussed plans for security review of xsnap:

 - [x] #2469 review of Agoric additions to xsnap
 - [x] #2466 XS library security audit Epic
   - [x] #2467 XS library security audit definition
 - [x] #2470 xsnap authority
 - [x] #2471

**Comment by dckc** [comment]
I'd like to make some progress on xsnap code organization ([endo Issue \#681](https://github.com/endojs/endo/issues/681)) before the audit

**Comment by dckc** [comment]
#2466 should probably stay open until the report is published, but this wrapper Epic is no longer worth tracking separately.
