### ISSUE TITLE
commit to XS

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2473]
- [x] limits - string size, number of properties #2681 
   - gather experience using benchmarks
 - [ ] metering  #2972 
     - [ ] sound
 - [ ] XS based testnet / devnet experience #2521
 - [x] [Error stacks](https://github.com/tc39/proposal-error-stacks)
     - fallback: debug on node

Postpone:
   - deterministic metering #2776 
       - [x] https://github.com/Moddable-OpenSource/moddable/issues/564
   - sloppy metering #2979 
 - run agoric-sdk, SES-shim tests on XS #370 - we ran most of the tests but have yet to land regular CI
   - [SES-shim/issues/535](https://github.com/Agoric/SES-shim/issues/535) running ava tests on XS
would be nice:
 - [SES-shim/issues/536](https://github.com/Agoric/SES-shim/issues/536) module support in XS Compartment
   - work-around: rollup / bundleSource

related:
 - determinism of weakref finalization

**Comment by dckc** [comment]
sync w/@warner on switching to XS ... _moved to #2521_
