### ISSUE TITLE
XS based testnet / devnet experience

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2521]
## What is the Problem Being Solved?

We lack experience with performance, size limits (#2652 ), etc. using XS in validators.

## Test Plan

sync w/@warner on switching to XS (perhaps not exactly the same as committing to XS, but close):

 - [x] vat creation in crank is #2911 #2928 pending review.
 - [x] removing tests that we don't want to make work on XS
   - [x] removing within-vat metering #2952
     - [x] spawner to use createVat #2941 failing a test
 - [x] test that metering catches runaways on XS.
 - [x] test that metering catches allocation overrun on XS. #2972
 - [x] don't force local when metering
 - [x] remove assert !metering in manager-subprocess-xs
 
 - [x] refactor dispatch #2671 is landed.

_Apr 23 plan moved from https://github.com/Agoric/agoric-sdk/issues/2473#issuecomment-825847899_

**Comment by dckc** [comment]
I'm starting to gather experience (see branch from #2686 ).... mostly with a fake chain so far, but I'm looking into "scenario2" and genesis and such.

In this branch, the vat name shows up in `ps`. `watch -n 1 pstree --arguments --show-pids --hide-threads $shell` (where `$shell` is the pid of the parent shell of the agoric start command) is handy:

```
Every 1.0s: pstree --arguments --show-pids 13199                        jambox: Fri Mar 19 02:48:56 2021

bash,13199
  `-node,17994 /home/connolly/projects/agoric/agoric-sdk/packages/agoric-cli/bin/agoric --sdk start ...
      |-node,18044...
      |   |-xsnap,18094 v5:bootstrap -l100
      |   |-xsnap,18095 v1:host -l10000000
      |   |-xsnap,18096 v2:http -l10000000
      |   |-xsnap,18097 v3:network -l10000
      |   |-xsnap,18098 v9:timer -l1000000
      |   |-xsnap,18099 v4:uploads -l10000
```

cc @michaelfig @ski

**Comment by dckc** [comment]
@warner #2686 is landed now, so you can do stuff like run `agoric start` or `scenario2` on XS by setting `SWINGSET_WORKER_TYPE=xs-worker`.

As noted above, to confirm that it's doing so: `watch -n 1 pstree --arguments --show-pids $shell`.

**Comment by dckc** [comment]
remaining work is tracked elsewhere.
