### ISSUE TITLE
Examine Dapps to see if any changes are needed for Nat 4.0.0

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2555]
## What is the Problem Being Solved?

We updated any dapps which have tests and CI running on agoric-sdk, but we should examine all the dapps to ensure that they work.

- [x] dapp-fungible-faucet
- [x] dapp-card-store
- [x] dapp-otc
- [ ] dapp-oracle
    Oracle needs some more work to properly do the 18-digit $LINK, but that should be coordinated with Chainlink changes, so it can wait.
- [x] dapp-pegasus
- [x] dapp-encouragement
- [ ] dapp-autoswap ([errors on sendBroadcast](https://github.com/Agoric/dapp-autoswap/issues/19))
- [ ] dapp-simple-exchange ([errors on sendBroadcast](https://github.com/Agoric/dapp-simple-exchange/issues/25))
- [x] dapp-svelte-wallet
- [x] dapp-token-economy https://github.com/Agoric/dapp-token-economy/issues/121
- [x] documentation
