### ISSUE TITLE
Devnet upgrade

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2608]
Plans for the next software release (targeting 2020-03-16):
- [ ] deployment script with options: archiving? validator? rpc? seed? network-config: unlisted/public/persistent_peer
- [ ] configure a prepared genesis.json
- [x] Move to `devnet.agoric.net` and `devnet.explorer.agoric.net`
- [x] Incorporate Gaia hot fix (v4.0.1)
- [x] Incorporate Tendermint patch to prevent missed blocks described by https://github.com/tendermint/tendermint/pull/6204#issuecomment-794196815
- [x] kwun/stargate branch of Big Dipper forbole/big-dipper#478
- [x] ~~@katelynsills New static AmountMath Agoric/agoric-sdk#2600 Agoric/agoric-sdk#2601~~ static AmountMath implementation is available
- [x] ~~Have SwingSet allow eventual sends to Symbol-named methods #2481~~ We currently work correctly with `Symbol.asyncIterator` and reject promises with other Symbol-named methods.

**Comment by erights** [comment]
> Have SwingSet reject eventual sends to Symbol-named methods (@FUDCo please make an issue for this)

Any chance we could get https://github.com/Agoric/agoric-sdk/issues/2092 fixed in time for that instead? IIRC, the changes needed were expected to be local and minor, yes?

**Comment by michaelfig** [comment]
Done.
