### ISSUE TITLE
Integrating Pegasus for IBC transfer

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2847]
## What is the Problem Being Solved?

Our current integration of Pegasus with the Agoric chain's IBC uses an unusual port name (not `"transfer"`) and an unusual recipient address format (not `"agoric1..."`).  This causes trouble for the [Keplr wallet](https://keplr.app) which assumes the usual names.  Although it would improve Keplr not to be dependent on these conventions, we want to make our chain conform to them for expedience and less surprise to the user.

## Description of the Design

- [x] Enable Pegasus to look up non-boardID recipients by bech32 in `E(home.namesByAddress).lookup('agoric1...', 'depositFacet')`, as well as continuing to support boardID recipients (Agoric/dapp-pegasus#28)
- [x] Change wallet backend to register deposit facet under `E(home.myAddressNameAdmin).update('depositFacet', facet)` (#2853)
- [x] Change wallet frontend to display `E(home.myAddressNameAdmin).getMyAddress()` for Self-contact. (#2853)
- [x] Move `dapp-pegasus/contract` to `agoric-sdk/packages/pegasus`. (#2857)
- [x] Install Pegasus during chain bootstrap, and listen on the `"pegasus"` IBC port. (#2857)
- [x] Move the Golang `x/ibc/application/transfer` IBC port from `"transfer"` to `"cosmos-transfer"`.  Move Pegasus to the `"transfer"` IBC port. (#2861)
- [x] Test with Keplr. (#2861)

## Test Plan

Start a local Agoric chain with the above changes, create an IBC channel to its `"transfer"` port, and use Keplr to transfer tokens from an existing public chain (maybe the unmodified Agoric devnet) to that local Agoric chain.  Verify that the tokens appear as payments in the local wallet.

**Comment by michaelfig** [comment]
Done!
