### ISSUE TITLE
Zoe Memory Usage: Analysis and Task List

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2880]
# Analysis

- 1 ZoeService
- 1 ZCF Bundle
- Installations
- Instances
  - each associated with one installation. Can have many instances per installation. Some installations won’t have instances.
  - Can distinguish between contracts intended to have many instances (coveredCall) and contracts that are intended to only have one instance (AMM)
- issuers, brands, and purses (plus replication in ZCF per instance where used).
  - One purse per issuer, but the issuers and brands are stored once in Zoe and replicated in ZCF for every usage in contract instance. The issuers and brands in Zoe are shared by all contract instances.
- invitations
  - Can have many invitations per instance. Invitations are payments, so are already virtual objects.
- seats
  - Not all invitations are turned into seats, and not all seats have an invitation.

Further specifics and internal objects:
- Zoe Instance Admin
  - 1 per instance
- Zoe Instance Admin for ZCF
  - 1 per instance
- ZCF Vat
  - 1 per instance. Could be divided up into a `setup` phase which could be made into a "zygote" and the `executeContract` phase where the ZoeService sends the contract code bundle and the `instanceRecord` (terms, issuers, brands, etc).
- HandleOfferObj (aka addSeatObj)
  - 1 per instance. Used for Zoe to tell ZCF to handle an incoming offer. Only communication path from Zoe to ZCF after contract is executed, all other communication is the other direction.
- InvitationHandle
  - 1 per invitation. Stored in ZCF mapped to the offerHandler function.
- SeatHandle 
  - 1 per offer, internal only for communication between Zoe and ZCF about a seat.
- Zoe Seat Admin
  - 1 per offer. Like all internal seat objects, it's only made after escrow, not when invitation is made.
- User Seat
  - 1 per offer. 
- ZCF Seat
  - 1 per offer.

## Questions

- What objects can be virtual objects now?
- How can we reduce the references to objects after usage to enable garbage collection?
- (for future thought) How can we allow users to intentionally delete state? For example, uninstall a Zoe installation that they created? We can already shutdown a ZCFVat.

## Tasks

- [x] Refactor for ease of understanding and analysis
  - [x] Add unit tests for the refactored pieces
- [ ] Make ZoeSeatAdmins virtual objects
- [x] Drop ZoeSeatAdmins after the ZCFSeats exits or fails.
- [x] ~~Make ZCFSeatAdmins virtual objects~~
- [x] ~~Drop ZCFSeatAdmins after the ZCFSeat exits or fails~~.
- [x] Drop ZCFSeat after seat exits or fails.
- [x] Drop the invitationHandle from the invitationHandleToOfferHandler weakStore after the offer is made.
- [ ] Drop ZoeInstanceAdmin in Zoe after ZCF Vat shutdown.
- [x] Drop SeatStaging from WeakSet after use in reallocation
- [x] Divide up ZCF execution into execution that occurs before any contract specific data is known and execution that happens when the contract is supposed to be run
- [ ] (Nice to have) Find a way to drop UserSeats while allowing users to still query for the final allocation
- [ ]  ~~Drop the seatStaging if the associated seat no longer exists~~
- [ ] Drop SeatHandleToZoeSeatAdmin if seat has exited

Tasks involving user-exposed objects that require that virtual objects support `===`:
- [ ] Make purses virtual objects
- [ ] ~~Make SeatStagings virtual objects~~
- [ ] Make ZCFSeats virtual objects
- [ ] Make UserSeats virtual objects

**Comment by erights** [comment]
> Currently, virtual objects cannot be compared with === (confirmed with Chip)

@FUDCo is currently working on this. We are now confident they will be `===`
