### ISSUE TITLE
Genesis checklist

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3015]
Before genesis:
- [x] Parameters for distribution/mint and governance need to be set @rowgraus 
- [x] Create genesis accounts with 75 BLD allocated
- [x] Collect gentxs from validators

After genesis 
- [ ] Provision each validator with an ag-solo client including virtual purse for RUN
