### ISSUE TITLE
Capitalize AmountMath but leave camelCase version for now

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3045]
@dtribble suggested capitalizing `AmountMath`, since it is similar conceptually to `Math.` We will want to make sure that we leave the camelCase version `amountMath` for now, so that there are no breaking changes. 

This task can be divided up into the following PRs:

- [x] Introduce the new capitalized AmountMath and mark the other version as `@deprecated`
- [x] Update documentation to the new capitalized AmountMath and mention the old version is deprecated
- [x] Change all of agoric-sdk to use the new capitalized version (#3088)
- [x] Change the dapps and any other known usages to use the capitalized version (#3089)
- [x] Eventually, a long time from now, remove the deprecated camelCase
