### ISSUE TITLE
RUNstake: borrow RUN against staked BLD

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#3788]
## What is the Problem Being Solved?

per [RUNStake User Stories](https://docs.google.com/document/d/19xP4AjLDdHvlGYFyC_Yq3Opp7oR60rRc-9UKAyb26a4/edit#heading=h.ekia0c1wmi3q) section by @rowgraus and co 5 Apr:

As a BLD staker with no RUNstake position, I need to be able to open a position by placing a lien on my staked BLD and receiving RUN
 - Process should feel familiar to vaults
 - Subject to RUN per BLD limits
 - Subject to asset level debt limit

As a BLD staker with an existing RUNStake position, I need to be able to manage it; that is: adjust my RUN debt and BLD lien within the bounds of the contract.
 - Process should feel familiar to vaults

As a BLD staker with an existing RUNStake position, I need to be able to close it entirely
 - May be combined with/handled by the ‘manage’ use case above

## Description of the Design

Like vaultFactory, the runStake contract provides loans and charges interest and minting fees; differences include:
  1. The loan is secured by a lien on staked BLD, not by transferring collateral.
  2. There is no liquidation. Instead, the staked BLD generates a stream of RUN rewards which can be used to pay down the debt. (See #4244 for more on that part.)

Design notes in [runStake/README.md](https://github.com/Agoric/agoric-sdk/blob/master/packages/run-protocol/src/runStake/README.md) include a sequence diagram of interactions between a user/dapp, walletBridge, runStake (and attestation), and Cosmos SDK.

We use a semi-fungible `copyBag` token to represent lien attestations: the items is the address where BLD is staked and the quantity is the lien (delta).

 - [x] add `getLiened()` to [attMaker](https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/zoe/src/contracts/attestation/attestation.js#L97) so the wallet can get it before taking out a loan.

related work:

 - #3277
 - #4165
 - #4245
 - #4244
 - #4263
 - #3991 

## Security Considerations

 - line of credit involves use of the RUN mint
 - BLD liens merit care

## Test Plan

 - [x] [RUN LoC Test Cases \- Google Sheets](https://docs.google.com/spreadsheets/d/1XC754C9d6KyEuYkMjrSWNi5xDSvnL6-oc8DQw26vtn4/edit#gid=0)
   - [x] payback
 - [x] use governance for minting ratio
 - [x] charge interest
 - [x] Attestation tokens control liens
 - [x] bootstrap provides `attestationMaker` to each `home.wallet` as in https://github.com/Agoric/agoric-sdk/issues/3788#issuecomment-994100862
 - [ ] notifier for wallet (#4263)
 - [x] `local-chain` governance testing documentation
 
nice to have:
 - [ ] generate sequence diagram from a test and check against runstake/README.md

**Comment by dckc** [comment]
With @JimLarson and @Chris-Hibbert , I drew a sequence diagram on a whiteboard. I'm trying to refine it closer to the details of our platform.

![IMG_20211021_133921418](https://user-images.githubusercontent.com/150986/138724564-372b6211-5103-49b3-a176-06433ed24ac0.jpg)


```puml
@startuml runLoC

treasury -> walletBridge: getPurseBalance("BLD")
walletBridge --> treasury: 5000

treasury -> attestation: getMax(ag123)
attestation -> golang: getAccountState(ag123)
golang --> attestation: "4000 BLD liened"
attestation  --> treasury: "4000 BLD liened"

treasury -> attestation: getReturnableAttestation(450 RUN)
attestation -> golang: setLienedAmount(4500 BLD)
golang --> attestation: yes

treasury -> attestation: give: 0; want: attestation 450
attestation --> walletBridge: attestation 

walletBridge -> runLoC: attestation 

runLoC -> priceAuthority: BLD price?
priceAuthority --> runLoC: 0.50RUN

runLoC -> mintRUN: mintGains(450)
mintRUN --> runLoC: 450RUN

runLoC --> walletBridge: 450RUN

@enduml

```

![runLoC](https://user-images.githubusercontent.com/150986/138724542-b1c2ebdd-8139-46a8-a1cb-ee7d83032d8d.png)

**Comment by dckc** [comment]
refined in discussion...

```
@startuml runLoC

treasury -> walletBridge: getPurseBalance("BLD")
walletBridge --> treasury: 5000
note right
collateralization rate: 10x
BLD price 0.5RUN
end note

treasury -> attestation: getMaxAvailable(ag123)
attestation -> golang: getAccountState(ag123)
golang --> attestation: "4000 BLD liened"
attestation  --> treasury: "4000 BLD liened"

treasury -> attestation: getReturnableAttestation(500 BLD)

note right
user asks for 25 RUN
end note

attestation -> golang: setLienedAmount(4500 BLD)
golang --> attestation: yes

attestation -> treasury: attestation 500 BLD

treasury -> runLoC: give: attestation 500 BLD; want: 25 RUN
note right
user may "want" less than the full line
end note


runLoC -> mintRUN: mintGains(25)
mintRUN --> runLoC: 25RUN

runLoC --> walletBridge: 25RUN

@enduml
```

### amount borrowed vs. amount liened

amount borrowed should be adjustable independent of amount liened. hm.
nice-to-have

### authority to create a lien

in the user bundle?

**Comment by dckc** [comment]
1st draft of run LoC:

https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/treasury/src/runLoC.js
https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/treasury/test/test-runLoC.js

_TODOs are tracked in the comment description_

**Comment by dckc** [comment]
I had the impression that getting a RUN LoC would require the user to accept 2 offers:
 1. to get an attestation (which creates a lien against their BLD)
 2. to trade the attestation for some RUN

and then another 2 to release the lien:
 1. to pay off the line of credit and get the attestation back
 2. to return the attestation and release the lien

After discussion with @Chris-Hibbert and reviewing the code, we determined that getting an attestation doesn't involve an offer. Just like the wallet takes offer descriptions from dapps and makes them into actual offers by filling in payments taken from purses, the wallet should fill in an attestation payment by getting an attestation. (_IOU a separate **wallet** issue._) Bootstrap will have to provide the wallet with an `attestationMaker` bound to the user's cosmos address.

The attestation contract currently uses invitations / offers to return attestations, but it might as well just have a public API method to do so. Then, just like the wallet takes payouts and puts them in a user's purse, it should recognize attestation payouts and return them using the public method.

cc @samsiegart @michaelfig @rowgraus @dtribble @JimLarson

**Comment by dckc** [comment]
## Brainstorm: Virtual Purses for Extendable Liens

_the main limitation of the existing attestation-based design, that the lien has to be paid off before it can be extended, has been escalated to its own issue: #4245_

notes from discussion with @samsiegart on novel purse in place of `attMaker`...

```js
// both do
publicLienableBLDBrand = board.get...;

// wallet does
purse2 = home.myBLDVirtualPurse
purse3 = home.myLienableBLDVirtualPurse

purse3.getCurrentAmount() === { brand: home.myPersonalBrand, value: 6000n };
display(purse3.getCurrentAmount()) // cross golang bridge
// display 0 liened instead of 6000 lienable?

// dapp does
attAmount = {brand: publicLienableBLDBrand, value: 4000n};
walletBridge.suggestOffer({ give: { Attestation: attAmount });

// wallet does
if (amount.brand === publicLienableBLDBrand) { // or: if (invitation is from RunLoC) { ...?
  const myAmount = { brand: home.myPersonalBrand, value: amount.value}
}
pmt = purse3.withdraw(myAmount) // golang setLien(4000)

E(zoe).offer(... { give: { Lien: pmt }, want: { RUN: run(100) }});

purse3.getCurrentAmount() === { brand: home.myPersonalBrand, value: 2000n };

// to release the lien:
purse3.deposit({ brand: home.myPersonalBrand, value: 4000n]})

// to decrease the lien:
purse3.deposit({ brand: home.myPersonalBrand, value: 1500n]})
```

_p.s. switching out the brand wouldn't preserve offer-safety. The dApp would have to use myPersonalBrand too._

**Comment by JimLarson** [comment]
Note that attempting to decrease or release the lien could fail unless the current debt is low enough. Also, the available-to-lien balance is `accountState.Bonded - accountState.Liened`, which could be negative in cases of unbonding or slashing. If the balance is limited to a Nat, then there will be the case where the balance is zero, but remains zero after a nonzero deposit. There will have to be an additional information source to show the remaining negative balance.

**Comment by dckc** [comment]
sync'd up with @samsiegart . For a getRUN demo, we have a bunch of pieces missing:

 - [x] demo getRUN
   - [x] get an attestation
     - [x] have golang bridge
     - [x] get attMaker
       - [x] start getRUN contract
         - [x] not implemented in local-chain golang mode
     - [x] stake some BLD
       - ~~flesh out tapFaucet stub~~
   - [ ] https://github.com/Agoric/dapp-treasury/issues/64
   - [x] expose attMaker to wallet, not just home
   - [x] semi-fungible tokens #4361 
 
cc @michaelfig @rowgraus

**Comment by dckc** [comment]
@michaelfig and I worked out an approach using `local-chain` mode (hence with the golang bridge). Using the code I just pushed to #4092, we start the chain using `decentral-demo-config.json` thus:

```
cd dapp-directory
CHAIN_BOOTSTRAP_VAT_CONFIG=@agoric/vats/decentral-demo-config.json agoric start local-chain --reset -v >,local-chain.log 2>&1 &
```

That version of bootstrap starts the economy.

Then we start our `ag-solo`:

```
agoric start local-solo --reset -v
```

`home.attMaker` was added as part of starting the economy, but when we try to make an attestation, we recall that we have no BLD staked:

```

command[3] E(home.myAddressNameAdmin).getMyAddress()
history[3] "agoric1h5e69sgw9nygtealll0hhkc53pkwxs3vtspt8l"

command[4] home.attMaker
history[4] [Object Alleged: attMaker]{}

command[5] E(home.agoricNames).lookup('brand', 'BLD')
history[5] [Object Alleged: BLD brand]{}

command[6] brand = {BLD: history[5]}
history[6] {"BLD":[Object Alleged: BLD brand]{}}

command[7] E(home.attMaker).makeAttestation({brand: brand.BLD, value: 100n})
history[7]
Promise.reject("Error: Only (an object) was bonded and unliened, but an attestation was attempted for (an object)")
```

We get provisioned with 13BLD (13_000_000 ubld). We [stake](https://hub.cosmos.network/main/delegators/delegator-guide-cli.html#sending-transactions) 9BLD:

```
# put agd in our path
export PATH=~/projects/agoric/agoric-sdk/golang/cosmos/build/:$PATH

# get our local key name (ag-solo)
agd keys list --home=_agstate/agoric-servers/local-solo-8000/ag-cosmos-helper-statedir --keyring-backend=test

# get validator address:
agd --home=_agstate/agoric-servers/local-solo-8000/ag-cosmos-helper-statedir query staking validators

# stake 9BLD:
agd --home=_agstate/agoric-servers/local-solo-8000/ag-cosmos-helper-statedir --keyring-backend=test tx staking delegate  agoricvaloper1jnvutw68khpeshvcrxychpz9y8ztp4nfwyl8dt 9000000ubld --from ag-solo --gas auto --gas-adjustment 1.5 -b block --chain-id agoric
```

Now we can get an attestation in the REPL:

```
command[8] E(home.attMaker).makeAttestation({brand: brand.BLD, value: 6000000n})
history[8] [Object Alleged: BldLienAtt payment]{}
```

**Comment by dckc** [comment]
TODO:
 - add `getLiened()` to [attMaker](https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/zoe/src/contracts/attestation/attestation.js#L97) so the wallet can get it before taking out a loan.

_note from discussion with @samsiegart_

**Comment by dckc** [comment]
_moved to https://github.com/Agoric/agoric-sdk/issues/4263#issuecomment-1045673702_

**Comment by dckc** [comment]
### attMaker.getLiened() and attMaker.getAccountState()

c8526551c

@samsiegart I added `attMaker.getLiened()` as we discussed. I also added `attMaker.getAccountState()` while I was at it:

The `local-solo` provisioning process gets us 13BLD:
```
command[1] home.attMaker
history[1] [Object Alleged: attMaker]{}
command[2] E(home.attMaker).getAccountState()
history[2] {"bonded":{"brand":[Object Alleged: BLD brand]{},"value":0n},"currentTime":1645245321n,"liened":{"brand":[Object Alleged: BLD brand]{},"value":0n},"locked":{"brand":[Object Alleged: BLD brand]{},"value":0n},"total":{"brand":[Object Alleged: BLD brand]{},"value":13000000n},"unbonding":{"brand":[Object Alleged: BLD brand]{},"value":0n}}
```

Then, after we delegate 9 as above:

```
command[3] E(home.attMaker).getAccountState()
history[3] {"bonded":{"brand":[Object Alleged: BLD brand]{},"value":9000000n},"currentTime":1645245582n,"liened":{"brand":[Object Alleged: BLD brand]{},"value":0n},"locked":{"brand":[Object Alleged: BLD brand]{},"value":0n},"total":{"brand":[Object Alleged: BLD brand]{},"value":13000000n},"unbonding":{"brand":[Object Alleged: BLD brand]{},"value":0n}}
```

We have not yet liened any BLD:

```
command[5] E(home.attMaker).getLiened()
history[5] {"brand":[Object Alleged: BLD brand]{},"value":0n}
```

Now let's get an attestation for a lien against 4 BLD and look at the amount of the attestation:

```
command[7] BLD = { brand: history[5].brand }
history[7] {"brand":[Object Alleged: BLD brand]{}}
command[8] E(home.attMaker).makeAttestation({ brand: BLD.brand, value: 4n * 10n**6n})
history[8] [Object Alleged: BldLienAtt payment]{}
command[9] E(home.agoricNames).lookup('issuer', 'Attestation')
history[9] [Object Alleged: BldLienAtt issuer]{}
command[10] Attestation = { issuer: history[9] }
command[11] E(Attestation.issuer).getAmountOf(history[8])
history[11] {"brand":[Object Alleged: BldLienAtt brand]{},"value":[{"address":"agoric1t766thzzn795q4n86xq9834dep3j27edvvyfdn","amountLiened":{"brand":[Object Alleged: BLD brand]{},"value":4000000n}}]}
```

_Now_ `getLiened` tells us something non-trivial:

```
command[12] E(home.attMaker).getLiened()
history[12] {"brand":[Object Alleged: BLD brand]{},"value":4000000n}
```

And just for completeness:

```
command[13] E(home.attMaker).getAccountState()
history[13] {"bonded":{"brand":[Object Alleged: BLD brand]{},"value":9000000n},"currentTime":1645246045n,"liened":{"brand":[Object Alleged: BLD brand]{},"value":0n},"locked":{"brand":[Object Alleged: BLD brand]{},"value":0n},"total":{"brand":[Object Alleged: BLD brand]{},"value":13000000n},"unbonding":{"brand":[Object Alleged: BLD brand]{},"value":0n}}
```

**Comment by dckc** [comment]
demo: Feb 18 [37 min recording](https://agoric.zoom.us/rec/share/I2GsNfmsWXETI3qDSzOR7DxB3OurshYom1Ign0M2un7DokInwLJToeHEqgmFXJFa.hU1m3sLTg8_KuwZF?startTime=1645248111000)
Passcode: `iM#MURR6`

**Comment by dckc** [comment]
### Zoe best practices?

modulo rewards (#4244) I'm down to the last of the 18 cases in our design spreadsheet.

For a contract that should have been "60 lines of JavaScript", it sure is a lot:

 - 326 [getRUN.js](https://github.com/Agoric/agoric-sdk/blob/dc-getRUN/packages/run-protocol/src/getRUN.js)
 - 334 [attestation.js](https://github.com/Agoric/agoric-sdk/blob/dc-getRUN/packages/run-protocol/src/attestation/attestation.js)

It feels somewhat repetitive and verbose. Are there better ways of doing this stuff, I wonder? I suppose I'll find out in code review...

**Comment by dckc** [comment]
RUNStake should use a “minting ratio” rather than a ratio + price.

governance of it is related to money supply, but there's a risk of losing parity.

**Comment by dckc** [comment]
Another restival note:
Deal with risk of mintGains succeeding when reallocate fails
If mint gains happens before reallocate, someone can make an offer they know will fail and the minting will have happened
Could be mitigated with a conventional helper
Or prevented through change in ocaps
Will probably be addressed in a redesign of reallocate to drop stagings

**Comment by dckc** [comment]
I spent a little time this week with @andrey-kuprianov of @informalsystems building a diagram. Thanks, @arirubinstein , for transcribing it to mermaid:
https://gist.github.com/arirubinstein/8a87ded49744a38861b6ec8697a6191e

cc @jessysaurusrex

**Comment by jessysaurusrex** [comment]
My new security pitch about diagramming in five words:

Agoric: We have art projects 🎨

**Comment by turadg** [comment]
Another diagrams (from https://github.com/Agoric/agoric-sdk/pull/4741#issuecomment-1075530415 )

```mermaid
sequenceDiagram
    actor dapp
    participant walletBridge
    participant attestation
    participant runStake
    participant golang

    note right of dapp: How dapp finds the current state

    note right of walletBridge: walletBridge is provided to dapps and controlled by Wallet UI
    dapp ->>+ walletBridge: getPurseBalance("BLD")
    dapp -->> walletBridge: 5000

    note right of attestation: ag123 is a cosmos address
    dapp ->> attestation: getMax(ag123)
    attestation ->> golang: getAccountState(ag123)
    note right of golang: Cosmos supports lien
    golang -->> attestation: account status in which 4000 BLD liened
    attestation  -->> dapp: account status in which 4000 BLD liened
    note right of dapp: Treasury now knows

    note right of dapp: Want to get 450 RUN by liening 500 BLD
    dapp ->> walletBridge: getReturnableAttestation(want: 450 RUN, give: 500 BLD-Att)
    note right of walletBridge: Blocks on user approval in wallet
    walletBridge ->> attestation: makeAttestation(500 BLD)
    attestation ->> golang: setLienedAmount(4000 + 500 BLD)
    golang -->> attestation: ACK or throws

    attestation -->> walletBridge: Payment of 500 BLD-Att liened on ag123

    walletBridge ->> runStake: offer w/payment for {give: 500 BLD-Att, want: 450 RUN} 

    runStake --> walletBridge: Payment for 450RUN and offerResult
    walletBridge --> dapp: notifiers from offerResult
```

**Comment by Tartuffo** [comment]
@dckc is #3991 no longer a blocker?  What more needs to be done to close this out?

**Comment by dckc** [comment]
> @dckc is #3991 no longer a blocker?

I don't think so, but that's a product requirements question; it's not my role to decide.

> What more needs to be done to close this out?

Good question. I'm struggling to figure out the scope of this issue. It could be as small as the contract component (which is done, or at least: merged to master) or it could include integration with the wallet and bootstrap.

More later...

**Comment by samsiegart** [comment]
> Good question. I'm struggling to figure out the scope of this issue. It could be as small as the contract component (which is done, or at least: merged to master) or it could include integration with the wallet and bootstrap.

+1 for smaller scoped issues, it's easier to understand what is and isn't done that way

**Comment by dckc** [comment]
empty bug: https://gist.github.com/samsiegart/da0a5a519cc20ec343d962abae1317ef

notifiers need to look like:
```js
    publicNotifiers: {
      vault: vault.getNotifier(),
      asset: assetNotifier,
    },
```
