### ISSUE TITLE
[Zoe] Autoswap: Allow users to create new liquidity pools in the same contract

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#391]
Our current implementation of autoswap assumes two kinds of tokens and one liquidity pool. We would like to allow users to create new liquidity pools for a new pair of tokens if the particular liquidity pool does not already exist. 

The end goal is that a user would be able to trade x for z by using two liquidity pools: (x, y) and (y, z).

Assumptions:
* Smart contracts will be instantiated with terms, which include an array of assays to start with.
* Contracts can reject these user defined terms and can reject offers. 
* Contracts can asynchronously add a new assay to the end of the canonical array of assays. This is not synchronous because the new assay may be remote so we must wait for the remote response.
* Contracts can have methods that allow external users to add assays to the contract. (Compare to the [Uniswap factory](https://github.com/Uniswap/contracts-vyper/blob/master/contracts/uniswap_factory.vy).)

The following changes are necessary to make this possible:

- [x] Allow users of smart contracts to make their offer rules with any order of assays #97
- [x] Allow users of smart contracts to make their payout rules for any subset of assays #392
- [x] Allow smart contracts to add assays to their canonical list. #380 
- [ ] Allow smart contracts to reallocate units for a subset of the canonical list of assays. (It's not clear whether this should be a helper filling out the unitMatrix or whether it should be built in.) #393

**Comment by katelynsills** [comment]
Closed by #861
