### ISSUE TITLE
SwingSet on xs: exploratory prototypes

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#47]
A key to Agoric's smart contract platform is compatibility between widespread understanding of best practices in JavaScript development with object capabilities and fail-stop deterministic execution. Initial development of [cosmic-swingset](https://github.com/Agoric/cosmic-swingset) is based on the popular and feature-rich node.js platform, but node.js represents an uncomfortably large amount of code to include in a trusted computing base as well as a substantial risk to deterministic execution. The xs engine in the [Moddable SDK](https://github.com/Moddable-OpenSource/moddable) is designed for constrained microcontroller environments. It has some limitations, but the supported feature set seems to be an excellent match for the Agoric platform.

### Issues (for reference)

 - [Agoric issues author:dckc](https://github.com/issues?q=is%3Aissue+archived%3Afalse+user%3AAgoric+author%3Adckc)
   - [Agoric issues commenter:dckc](https://github.com/issues?q=commenter%3Adckc+archived%3Afalse+user%3AAgoric+sort%3Aupdated-desc)
 - [Moddable-OpenSource author:dckc](https://github.com/issues?utf8=✓&q=is%3Aissue+archived%3Afalse+user%3AModdable-opensource+author%3Adckc+)

**NOTE:** In more recent designs, only vat workers run on XS, not all of SwingSet. See #2107 for details.

### Toward cosmic-swingset ag-solo on xs **OBSOLETE**

Current work is on ag-solo on xs. In particular, an [xs-lite](https://github.com/dckc/agoric-sdk/tree/xs-lite) branch where I'm integrating lessons from earlier "hack and slash" mode work ([xs-platform](https://github.com/dckc/agoric-sdk/tree/xs-platform) branch) without breaking the main build.

The pixel demo works thru getting a pixel balance but then loses its marbles with "key not found" stuff. I suspect / hope this is due to the promise queue priority issue #45.

#### Bootstrap documented in github actions

 - [x] github action workflow to test 2 packages
   - [x] script to generate manifest.json, main.js (see #370)
   - [x] github action: [ag-solo-xs.yml](https://github.com/dckc/agoric-sdk/blob/xs-lite/.github/workflows/ag-solo-xs.yml)
          - for example: [build log for 817d413](https://github.com/dckc/agoric-sdk/commit/817d413c65488ca4543f3fb192fa3ef73a935044/checks?check_suite_id=375331754)
     - [x] moddable SDK with `x-cli-lin`
       - [x] mainloop design #118 
       - [x] [moddable-linux-sdk.tgz](https://github.com/dckc/moddable/releases/download/ag08/moddable-linux-sdk.tgz) release ag08 ff41561
       - [build-release.yaml](https://github.com/dckc/moddable/blob/ag-linux-cli/.github/workflows/build-release.yaml)
       - see #118 for end-game
   - [x] PR to add xs build to regular testing (see #373)

### SwingSet unit testing on xs

A large part of the SwingSet test suite has been ported to xs:

| platform | branch | date | rev | scripts | tests | passing |
|----|----|----|----|----|----|----|
| node.js | master | Jan 17 | f833610831e6 | 20 | 755 | 755 |
| xs | xs-build-lite | Jan 18 | 5df242c2 | 12 | 594 | 594 |

 - 2 scripts are skipped due to the queue priority issue (#45)
 - 1 is skipped because the `build-bundle.js` tool I cribbed together doesn't grok `~.` yet
 - 5 are skipped because pre-bundling is incomplete

For more details, see [Jan 18 comment](https://github.com/Agoric/agoric-sdk/issues/47#issuecomment-575924734) below.

### tape testing work-alike: xs is ESM-only

One of main differences between node.js and xs is modules: xs supports only ES5 modules. Attempting to port tape showed extensive CommonJS dependencies. Incremental development of a work-alike, https://github.com/dckc/tape-xs , has worked reasonably well so far.

 - [x] tape initial port: https://github.com/dckc/tape-xs
   - [x] basics: equal, is, ok, notOk
   - [x] deepEqual, async
   - [x] count assertions
 - [ ] tape-xs issue: #370
 - [ ] #49 test scripts -> modules? actually, no...

### Using xs deep freeze for `harden()`

The `@agoric/harden` and `@agoric/make-hardener` code do extensive patching in a browser or node context to reach a state that seems to be essentially the default in the xs platform. xs has a [deep freezing](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/preload.md#deep-freezing) feature: `Object.freeze(x, true)` has an extra argument that, when set to `true`, seems to do the equivalent of `harden(x)`. Using deep freezing passes all the `@agoric/harden` tests but one.

 - [ ] https://github.com/Agoric/harden/issues/54 why complain about prototype not in roots?
 - [ ] https://github.com/Moddable-OpenSource/moddable/issues/303 non-determinism of %GeneratorFunction%[[Prototype]]
   - https://github.com/Agoric/harden/issues/47

**Comment by dckc** [comment]
## ag-solo on xs caught up with monorepo etc.

https://github.com/dckc/agoric-sdk/tree/xs-platform 757c337

run log:
https://gist.github.com/dckc/a5adf370abea5ab88a86a912e98e625d

I automated "all the vats and devices are rollup'd with filename conventions" in `ag-solo-xs.mk`

**Comment by dckc** [comment]
### toward github action for ag-solo on xs

My desktop gets more and more full of kludges. I haven't managed to coordinate with anyone else to reproduce my results, so let's try getting a robot to do it.

I got as far as one of the manual steps in my makefile:  **check out master and make scenario3-setup**

https://github.com/dckc/agoric-sdk/commit/d211823d7c20897aec2dbb60b95fd52c80edf18f/checks?check_suite_id=370981243

https://github.com/dckc/agoric-sdk/blob/ag-solo-xs-action/.github/workflows/ag-solo-xs.yml d211823

#### hanging at zoe vat

Ugh. After addressing various symptoms that I have seen locally, it's doing something I don't recall seeing before. I'm kinda stumped about where to go from here.

https://github.com/dckc/agoric-sdk/commit/d69140dc480199afab7eee857e2320b47b949a19/checks?check_suite_id=371898943

### heisenbug: `Cannot pass non-promise thenables`

After I filled in the `makeEvaluators` part of my ses port (9ce30d7), I started to get:

```
doProcess: vat[v15][o+0].bootstrap dispatch failed: Error: Cannot pass non-promise thenables {}
```

I worked on debug logging enough to learn that it was from the copy of marshal in bootstrap, and then set things aside yesterday. Now today I can't reproduce the problem. (Meanwhile, it looks like hp.resolve became HandledPromise.resolve in marshal 0.1.2, but that version isn't referenced in all the relevant places. (yet?))

Hence the motivation to get this stuff running somewhere other than my desktop.

**Comment by erights** [comment]
Hi @dckc the two are related. A bug in HandledPromise was causing handled promises not to be recognized as genuine promises, and therefore misclassified as non-promise thenables. Marshal, to avoid passing things with problematic behaviors, forbid non-promise thenables.

**Comment by dckc** [comment]
## github action for xs-lite

I'm trying a github action again with less invasive edits to moddable and agoric-sdk

So far: my version of moddable builds. I hope it got cached...

https://github.com/dckc/agoric-sdk/commit/88e8a532d321c35acd43dca7811c1e9c8a68d595/checks?check_suite_id=374897939

I got the `eventual-send` tests built; I think it runs, but since it never exits, the output doesn't seem to make it to the logs. Maybe I should make a separate issue for this event loop stuff...
https://github.com/dckc/agoric-sdk/runs/364252413

p.s.

## github action for 2 packages on xs (eventual-send, marshal)

Now that I got some moddable SDK stuff worked out ( https://github.com/Agoric/agoric-sdk/issues/118#issuecomment-569178998 ) the tests for these two packages run pretty cleanly:

https://github.com/dckc/agoric-sdk/blob/xs-lite/.github/workflows/ag-solo-xs.yml
https://github.com/dckc/agoric-sdk/commit/817d413c65488ca4543f3fb192fa3ef73a935044/checks?check_suite_id=375331754

  - [ ] report exceptions from main() in `lin_xs_cli.c`

**Comment by dckc** [comment]
@dtribble hot off the press: https://github.com/dckc/agoric-sdk/tree/xs-build-lite

ag-solo works correctly on xs in the case of ERROR:  . doesn't appear to be an ag-solo base directory 🙂

**Comment by dckc** [comment]
### ag-solo start seems to work on xs modulo web stuff
baa8348baa8348

run log: https://gist.github.com/dckc/5f2b521687f4fd022bc3dae30ec1c565

### express, morgan

8e9b9f4 has express (and serve-static), morgan, and http

### next: WebSockets

**Comment by dckc** [comment]
## Got a screen full of colored pixels!

It actually works sometimes, in the `x-cli-lin` build; I haven't seen it work in the debug setup.

### next: async http route methods

The moddable [http Server API](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/network.md#http-server) seems to require responses to be computed synchronously. I got away with that for static files, but the `put('/vat')` handler is async, so I'm just getting lucky somehow when it works.

### websocket handshake working

I get `ws.open!` in the browser console.

Hmmm... now I'm getting: `main.js:30 WebSocket connection to 'ws://localhost:8000/' failed: A server must not mask any frames that it sends to the client.`

e7b49bcce751

**Comment by dckc** [comment]
## SwingSet unit tests up to 594 / 594

CI build as of 5df242c: https://github.com/dckc/agoric-sdk/commit/5df242c22e894259b1caf65830d2b0030b69bf20/checks?check_suite_id=408373914

 - [x] test-comms {"pass":4,"fail":0,"total":4}
 - [x] test-controller {"pass":65,"fail":0,"total":65}
 - [ ] test-demos-comms **SKIP**:  build-bundle.js does not grok ~. yet
 - [ ] test-demos **SKIP**: test bundling WIP
 - [ ] test-devices **SKIP**:  test bundling WIP
 - [x] test-evaluate {"pass":69,"fail":2,"total":71}
 - [x] test-kernel {"pass":179,"fail":2,"total":181}
 - [x] test-liveslots {"pass":188,"fail":2,"total":190}
 - [x] test-marshal {"pass":202,"fail":2,"total":204}
 - [ ] test-message-patterns **SKIP**:  test bundling WIP
 - [ ] test-node-version **SKIP**:  see queue priority issue https://github.com/Agoric/agoric-sdk/issues/45
 - [x] test-promises {"pass":263,"fail":2,"total":265}
 - [ ] test-queue-priority **SKIP**: see queue priority issue https://github.com/Agoric/agoric-sdk/issues/45
 - [x] test-state {"pass":275,"fail":2,"total":277}
 - [x] test-timer-device {"pass":478,"fail":2,"total":480}
 - [x] test-transcript-light {"pass":537,"fail":2,"total":539}
 - [x] test-transcript {"pass":581,"fail":2,"total":583}
 - [x] test-vat-imports {"pass":588,"fail":0,"total":588}
 - [ ] test-vattp **SKIP**:  test bundling WIP
 - [ ] timer-device/test-device **SKIP**:  test bundling WIP

my local test log (with evaluate fix 3cdd017 and ses DEBUG turned on): https://gist.github.com/dckc/f600ecbc714b5b30c13924a2b0466ca1

**Comment by dckc** [comment]
My work on this issue is mostly standing by while the new SES / Compartment API are integrated into SwingSet; see #477

I have done a bit of work to keep my branch(es) up to date with master and I have worked with @michaelfig a bit on test debugging.

**Comment by dckc** [comment]
made a little progress on new-SES:

 - 7ac25880 * toward SwingSet/test on xs: build, link
 - 53cb51ab * SwingSet/test: test script compartment dependencies
 - 21f01a3d * xs-npm as of 11dd443 Jan 18, 2020
 - 350835b8 * SwingSet/test: toward test script Compartment API map (WIP)

https://github.com/dckc/agoric-sdk/tree/xs-new-ses

**Comment by dckc** [comment]
I sat down to resume work on this today given recent progress on new-SES etc. but re-discovered [ambient file access](https://github.com/Agoric/agoric-sdk/issues/66#issuecomment-548146394) in `SwingSet/src/controller.js` and lost momentum more or less right away. Sigh.

**Comment by dckc** [comment]
@dtribble @warner I'm inclined to change the scope of this to exploratory prototypes and close it in favor of #2107 and related stuff. OK?

I just reviewed the whole thing and I'm confident that there is no outstanding work represented _only_ in this ticket.

**Comment by dckc** [comment]
@warner agreed with closing this.
