### ISSUE TITLE
prune resolved Promises from liveslots/c-list/kernel tables

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#675]
subtasks, in likely implementation order:

- [x] #766 `dispatch.notifyResolve*` removes clist+liveslots entries (receiving side)
- [x] #767 `syscall.resolve*` removes liveslots+clist entries (sending side)
- [x] #769 remove Promise from `importedPromisesByPromiseID` table
- [x] #745 auto-subscribe vats when inbound clist entry is added
- [ ] #768 GC unreferenced kernel promise table entries

Another aspect of #513 is to prune resolved Promises from the system. In our current "small footprint" performance demo (a simple ping-pong message sent between a pair of Vats), each message sent creates a `result` Promise, and that causes a table entry to appear in the following places:

### liveslots

* the `valToSlot` WeakMap uses the application-visible `Promise` as a key, with the promise-id string (e.g. `p+3`) as the value, in case this Promise must ever be serialized in the arguments of some message
* the `slotToVal` Map uses `p+3` as the key, and the Promise as a value, so that inbound messages whose arguments reference this Promise can be deserialized correctly
* the `importedPromisesByPromiseID` Map uses `p+3` as the key, and a "promise record" (containing `{ p: Promise, res: resolverFunction, resPres: resolveToPresenceFunction, rej: rejectionFunction }`), so that an incoming `notifyResolveTo*` message can look up the correct resolver/rejector function to invoke.

### kernel

* for each Vat that has ever heard about the Promise, the kernel's C-List for that Vat will reference both the vat-specific identifier (`p+3`) and a kernel-wide identifier (e.g. `kp4`)
* the kernel promise table will have an entry for `kp4`, including its resolution status (unresolved, resolved to data, resolved to presence, forwarded to other promise, rejected with data)

In addition, the kernel promise identifier `kp4` may be referenced by other places within the kernel:

* it may be the target of one or more run-queue entries, either a message (sent to the promise), or a resolution notification (as the promise being resolved)
* it could appear in the arguments of a run-queue message or resolution notification
* for promise table entries that are unresolved, and for which the deciding vat does not implement Promise Pipelining, the table will include a queue of messages that should be delivered when the promise becomes resolved. These messages might reference the promise in an argument
* for resolved promise table entries, the resolution or rejection may include data, which can include a reference to the promise

![Swingset Resolved Promises - 1](https://user-images.githubusercontent.com/27146/76473104-b929aa00-63b4-11ea-8af3-73434b056a62.png)

## Current behavior

The ping-pong demo creates a new result promise for each message exchanged, which adds entries to all three liveslots tables (on both vats), as well as both kernel-side c-lists, and the kernel promise table. This promise is resolved (to `undefined`) a moment later, which causes a `notifyResolveToData` to be delivered, which calls the resolution function on the original result Promise. Our demo does not use `.then()`, so there are no callbacks to be run with the resolution. However, since we don't yet have a way to clean up these entries, they all just accumulate forever. We add roughly nine table entries per message.

With this cleanup implemented, the long-term memory usage should be constant, and the only disk storage growth over time should come from the transcripts.

## Necessary Changes

Our new contract between vats and kernels will be:

* when the kernel delivers `notifyResolveToData`/etc to a vat, it vows to never again reference the vat-specific promise identifier (`p+3`) which was resolved
  * the kernel enforces this vow by deleting the c-list entry just after mapping all slots of the message into vat-specific slots
* the vat receiving the notification vows to never again reference the identifier either
  * the vat enforces this by deleting the entry from all three of the liveslots tables: `valToSlot`, `slotToVal`, and `importedPromisesByPromiseID`
  * note that the data to which the promise is resolved might include this identifier, so the vat needs to unserialize the data into local Promises before deleting its table entries
  * likewise the vat needs to look up the resolver/rejector function before deleting the entry from `importedPromisesByPromiseID`

We need a similar vow in the other direction: when a vat calls `syscall.resolveToData`/etc, it should never again reference the promise identifier being resolved. We haven't thought through this case as carefully. There are two variants:

* The Promise is the result of an incoming method invocation and it gets resolved when that method returns (or when the Promise it returns gets resolved). The resolving Vat's application-level code never sees the Promise in question, so it has no opportunity to hold on to it for later. This is the easier case, as the three table entries are created and destroyed all within a single crank.
* The Promise was created locally, and then included as an argument in an outbound message send (or inside the result of some inbound method invocation). The kernel remembers the sending Vat as the decider for the Promise. That vat might send the Promise to arbitrary recipients, before or after it decides to resolve the Promise.

Our goal is to make the same vow: the vat will never again reference the vat-specific promise identifier after it makes the `syscall.resolve` which resolves it. And in exchange the kernel vows to never reference that identifier in any subsequent deliveries. The same sequence of events should happen: because the resolution might include data which includes the promise, the table entries must be deleted *after* the syscall is serialized.

(One open question is how to deal with mutual cycles in the resolution data: when two promises are resolved to arrays that each include the other. In general, delivery of a Promise that was previously deleted should be treated just as if the Promise had never been delivered yet: a new identifier is allocated for it, a `.then()` handler is attached, and when the callback fires, a resolution is delivered).

In addition, the kernel should be able to clean up its tables too. The kernel should maintain a reference count for each kernel promise identifier. Each c-list entry is one refcount, as is each run-queue item which references the promise-id (which might appear as the target of a message, or in the arguments). The promise table itself is the source of two other potential references: one for each message that is queued to some unresolved promise, and another for each resolved promise whose resolution (or rejection) data references the promise.

When this reference count drops to zero, the kernel can delete the promise-table entry, because at this point, nothing in the entire system can ever again reference the promise, so we no longer need to keep its resolution around. We should double-check the invariant that the promise is in a resolved state at this point: there should be no way for an unresolved promise to become completely unreferenced (the vat with decision-making authority should still have it in the c-list until it exercises that authority).

There remains a GC cycle problem: the only remaining reference might be from the promise's resolved-to-data value itself (`{ p, res } = makePromise(); res([p])`), or it might participate in a cycle that is limited to the kernel promise table (`{ p1, res1 } = makePromise(); { p2, res2 } = makePromise(); res1([p2]); res2([p1])`). Once all the vats are notified and the run-queue has drained, the c-lists and run-queue references will be removed, and the only remaining graph will not spread beyond the kernel's promise table. We will need some sort of mark+sweep GC to identify and delete these cycles. We might keep two references counts (one for just within the promise table, a second for references from c-lists and the run-queue), and only trigger this GC when a sufficiently large number of entries have zero external references but non-zero internal ones. We expect that this case will be rare (modulo denial-of-service attacks), so we can schedule it for a later milestone.

Note that deleting the vat-specific promise IDs from the c-lists (and liveslots tables) will happen well before the kernel promise table entry is deleted. There are plenty of message patterns which will cause the kernel to deliver a message that references a kernel promise ID which *used* to live in the c-list, but was since removed. This will simply generate a new c-list entry, a new vat-specific ID, and (since the promise is currently resolved) it will deliver both the referencing message and a `notifyResolveTo*` in quick succession. This should behave just like a normal vat creating a promise, resolving it, and only then sending the promise to another vat.

## code snippets

In `liveSlots.js`, we'll handle the inbound direction by changing `notifyFulfillToData` (and `ToPresence` and `Reject`) by adding the last four lines like so:

```js
  function notifyFulfillToData(promiseID, data) {
    insistCapData(data);
    lsdebug(
      `ls.dispatch.notifyFulfillToData(${promiseID}, ${data.body}, ${data.slots})`,
    );
    insistVatType('promise', promiseID);
    if (!importedPromisesByPromiseID.has(promiseID)) {
      throw new Error(`unknown promiseID '${promiseID}'`);
    }
    const val = m.unserialize(data);
    importedPromisesByPromiseID.get(promiseID).res(val);

    // add these:
    importedPromisesByPromiseID.delete(promiseID);
    const p = slotToVal.get(promiseID);
    valToSlot.delete(p);
    slotToVal.delete(promiseID);
    // beyond here, 'p' is a new Promise
  }
```

To handle the outbound direction (when this vat resolves a promise, and vows to never mention it again), we must change `thenResolve` to delete table entries just after calling `syscall.fulfillToPresence` or `fulfillToData`, and likewise change `thenReject` near its call to `syscall.reject`.

In the kernel, in `vatManager.js`, the inbound direction must change `deliverOneNotification` (which handles all four forms of resolution). For example the resolve-to-data case goes here:

```js
    } else if (kp.state === 'fulfilledToData') {
      const vpid = mapKernelSlotToVatSlot(kpid);
      const vatData = harden({
        ...kp.data,
        slots: kp.data.slots.map(slot => mapKernelSlotToVatSlot(slot)),
      });
      // HERE: delete vpid from clist, after mapping, before delivery
      await doProcess(
        ['notifyFulfillToData', vpid, vatData],
        `vat[${vatID}].promise[${vpid}] fulfillToData failed`,
      );
    } else if (kp.state === 'rejected') {
```

Deleting it from the c-list should (eventually) trigger a decrement-refcount action, which may then delete the entry from the kernel promise table. It's probably a good idea to defer this deletion until the vat interaction has finished.

The `vatManager.js` function `deliverOneMessage` will be modified to deal with the outbound direction.

**Comment by warner** [comment]
BTW this basically subsumes #25, but for now at least we aren't using a distinct "resolved promise" serialization type (I looked into that last summer and couldn't figure out how to make it work). Instead, we serialize Promises without paying attention to whether they're already resolved or not (since in many cases we cannot even ask this question synchronously). So liveslots serializes all Promises the same way, but for already-resolved ones, the `.then` callback fires a turn later, and we send a `syscall.resolve*` message into the kernel.

We should study the notes on #25 and see if there's anything additional we need to address here, then we can probably close it.

**Comment by FUDCo** [comment]
Superseded by #1124.  Closing.
